


.resknd_default_epopsadapter_multiprocess {
   background-image:url("images/resknd/default/16x16/EP Ops Adapter_MultiProcess.png") !important;
}

.resknd_custom_apposucp_ms_iis_websvc_cache {
   background-image:url("images/resknd/custom/16x16/APPOSUCP_ms_iis_websvc_cache.png") !important;
}

.resknd_custom_vcacadapter_vravmworld {
   background-image:url("images/resknd/custom/16x16/VCACAdapter_VRA VM WORLD.png") !important;
}

.resknd_default_epopsadapter_aix {
   background-image:url("images/resknd/default/16x16/EP Ops Adapter_AIX.png") !important;
}

.resknd_custom_container_department {
   background-image:url("images/resknd/custom/16x16/Container_Department.png") !important;
}

.resknd_default_epopsadapter_windows_fileservermount {
   background-image:url("images/resknd/default/16x16/EP Ops Adapter_Windows_FileServer Mount.png") !important;
}

.resknd_default_nsxtadapter_edgenode {
   background-image:url("images/resknd/default/16x16/NSXTAdapter_EdgeNode.png") !important;
}

.resknd_default_vcenteroperationsadapter_vc-ops-controller {
   background-image:url("images/resknd/default/16x16/vCenter Operations Adapter_vC-Ops-Controller.png") !important;
}

.resknd_default_container_vc-ops-self-monitoring {
   background-image:url("images/resknd/default/16x16/Container_vC-Ops-Self-Monitoring.png") !important;
}

.resknd_default_physicalsanadapter_nfsstorage {
   background-image:url("images/resknd/default/16x16/PhysicalSANAdapter_NFSStorage.png") !important;
}

.resknd_default_epopsadapter_solaris_fileserverfile {
   background-image:url("images/resknd/default/16x16/EP Ops Adapter_Solaris_FileServer File.png") !important;
}

.resknd_custom_container_businessservice {
   background-image:url("images/resknd/custom/16x16/Container_BusinessService.png") !important;
}

.resknd_custom_container_tier {
   background-image:url("images/resknd/custom/16x16/Container_Tier.png") !important;
}

.resknd_default_apposucp_postgresql {
   background-image:url("images/resknd/default/16x16/APPOSUCP_postgresql.png") !important;
}

.resknd_default_epopsadapter_solaris_networkserverinterface {
   background-image:url("images/resknd/default/16x16/EP Ops Adapter_Solaris_NetworkServer Interface.png") !important;
}

.resknd_default_nsxtadapter_managementnode {
   background-image:url("images/resknd/default/16x16/NSXTAdapter_ManagementNode.png") !important;
}

.resknd_default_physicalsanadapter_physicaldisk {
   background-image:url("images/resknd/default/16x16/PhysicalSANAdapter_PhysicalDisk.png") !important;
}

.resknd_default_vmware_lic_openinvsphere {
   background-image:url("images/resknd/default/16x16/VMWARE_LIC_OpenInVSphere.png") !important;
}

.resknd_default_nsxtadapter_loadbalancervirtualserver {
   background-image:url("images/resknd/default/16x16/NSXTAdapter_LoadBalancerVirtualServer.png") !important;
}

.resknd_default_vcacadapter_networkprofile {
   background-image:url("images/resknd/default/16x16/VCACAdapter_NETWORKPROFILE.png") !important;
}

.trvspec_default_remotechecks-epopsadapter-remotechecksworld {
   background-image:url("images/traversalspec/16x16/Remote Checks-EP Ops Adapter-Remote Checks World.png") !important;
}

.resknd_custom_apposucp_kong {
   background-image:url("images/resknd/custom/16x16/APPOSUCP_kong.png") !important;
}

.trvspec_default_nsx-ttransportzones-nsxtadapter-nsxtadapterinstance {
   background-image:url("images/traversalspec/16x16/NSX-T Transport zones-NSXTAdapter-NSXTAdapterInstance.png") !important;
}

.resknd_default_nsxtadapter_edgeclustergroup {
   background-image:url("images/resknd/default/16x16/NSXTAdapter_EdgeClusterGroup.png") !important;
}

.resknd_custom_apposucp_hadoop-hdfs {
   background-image:url("images/resknd/custom/16x16/APPOSUCP_hadoop-hdfs.png") !important;
}

.resknd_default_epopsadapter_solaris_fileserverphysicaldisk {
   background-image:url("images/resknd/default/16x16/EP Ops Adapter_Solaris_FileServer Physical Disk.png") !important;
}

.resknd_default_vcenteroperationsadapter_vc-ops-suite-api {
   background-image:url("images/resknd/default/16x16/vCenter Operations Adapter_vC-Ops-Suite-API.png") !important;
}

.resknd_custom_apposucp_activemq_broker {
   background-image:url("images/resknd/custom/16x16/APPOSUCP_activemq_broker.png") !important;
}

.trvspec_default_nsx-vspherelogicalswitches-nsxtadapter-nsxtadapterinstance {
   background-image:url("images/traversalspec/16x16/NSX-vSphere Logical Switches-NSXTAdapter-NSXTAdapterInstance.png") !important;
}

.resknd_default_vmware_hostsystem_power_unknown {
   background-image:url("images/resknd/default/16x16/VMWARE_HostSystem_power_unknown.png") !important;
}

.resknd_custom_epopsadapter_epopsadapterresourcesgroup {
   background-image:url("images/resknd/custom/16x16/EP Ops Adapter_EP Ops Adapter Resources Group.png") !important;
}

.resknd_default_fabricserver_zone {
   background-image:url("images/resknd/default/16x16/FabricServer_Zone.png") !important;
}

.resknd_default_apposucp_jboss {
   background-image:url("images/resknd/default/16x16/APPOSUCP_jboss.png") !important;
}

.resknd_default_nsxtadapter_transportzonegroup {
   background-image:url("images/resknd/default/16x16/NSXTAdapter_TransportZoneGroup.png") !important;
}

.resknd_default_vmware_datastore {
   background-image:url("images/resknd/default/16x16/VMWARE_Datastore.png") !important;
}

.adpknd_custom_vrbcadapter {
   background-image:url("images/adpknd/custom/16x16/vRBCAdapter.png") !important;
}

.resknd_custom_loginsightadapter_loginsightadapterinstance {
   background-image:url("images/resknd/custom/16x16/LogInsightAdapter_LoginSight Adapter Instance.png") !important;
}

.resknd_custom_container_geotag {
   background-image:url("images/resknd/custom/16x16/Container_GeoTag.png") !important;
}

.resknd_default_apposucp_sharepoint {
   background-image:url("images/resknd/default/16x16/APPOSUCP_sharepoint.png") !important;
}

.resknd_default_epopsadapter_linux_fileserverdirectory {
   background-image:url("images/resknd/default/16x16/EP Ops Adapter_Linux_FileServer Directory.png") !important;
}

.resknd_custom_apposucp_activemq_jvm_memory_usage {
   background-image:url("images/resknd/custom/16x16/APPOSUCP_activemq_jvm_memory_usage.png") !important;
}

.resknd_default_vmware_virtualmachine_power_standby {
   background-image:url("images/resknd/default/16x16/VMWARE_VirtualMachine_power_standby.png") !important;
}

.resknd_default_vcenteroperationsadapter_vc-ops-node {
   background-image:url("images/resknd/default/16x16/vCenter Operations Adapter_vC-Ops-Node.png") !important;
}

.resknd_custom_apposucp_rabbitmq_queue {
   background-image:url("images/resknd/custom/16x16/APPOSUCP_rabbitmq_queue.png") !important;
}

.resknd_custom_apposucp_pivotalserver_web_module {
   background-image:url("images/resknd/custom/16x16/APPOSUCP_pivotalserver_web_module.png") !important;
}

.resknd_default_vcacadapter_blueprint {
   background-image:url("images/resknd/default/16x16/VCACAdapter_BLUEPRINT.png") !important;
}

.trvspec_default_vspherehostsandclusters-vmware-vsphereworld {
   background-image:url("images/traversalspec/16x16/vSphere Hosts and Clusters-VMWARE-vSphere World.png") !important;
}

.adpknd_custom_loginsight {
   background-image:url("images/adpknd/custom/16x16/LogInsight.png") !important;
}

.resknd_default_vcenteroperationsadapter_vc-ops-fsdb {
   background-image:url("images/resknd/default/16x16/vCenter Operations Adapter_vC-Ops-Fsdb.png") !important;
}

.resknd_default_epopsadapter_linux_cpu {
   background-image:url("images/resknd/default/16x16/EP Ops Adapter_Linux_CPU.png") !important;
}

.resknd_default_epopsadapter_aix_fileserverphysicaldisk {
   background-image:url("images/resknd/default/16x16/EP Ops Adapter_AIX_FileServer Physical Disk.png") !important;
}

.resknd_custom_httppost_httppostadapterinstance {
   background-image:url("images/resknd/custom/16x16/Http Post_Http Post Adapter Instance.png") !important;
}

.resknd_default_epopsadapter_icmpcheck {
   background-image:url("images/resknd/default/16x16/EP Ops Adapter_ICMP Check.png") !important;
}

.resknd_default_apposucp_weblogic {
   background-image:url("images/resknd/default/16x16/APPOSUCP_weblogic.png") !important;
}

.resknd_default_epopsadapter_aix_fileservermount {
   background-image:url("images/resknd/default/16x16/EP Ops Adapter_AIX_FileServer Mount.png") !important;
}

.resknd_custom_apposucp_kafka {
   background-image:url("images/resknd/custom/16x16/APPOSUCP_kafka.png") !important;
}

.resknd_default_epopsadapter_windowsservice {
   background-image:url("images/resknd/default/16x16/EP Ops Adapter_Windows Service.png") !important;
}

.adpknd_default_pythonremediationvcenteradapter {
   background-image:url("images/adpknd/default/16x16/PythonRemediationVcenterAdapter.png") !important;
}

.resknd_default_vmware_networkfolder {
   background-image:url("images/resknd/default/16x16/VMWARE_NetworkFolder.png") !important;
}

.resknd_default_vcenteroperationsadapter_vc-ops-persistence {
   background-image:url("images/resknd/default/16x16/vCenter Operations Adapter_vC-Ops-Persistence.png") !important;
}

.resknd_custom_apposucp_couchbase {
   background-image:url("images/resknd/custom/16x16/APPOSUCP_couchbase.png") !important;
}

.resknd_default_physicalsanadapter_nfsvolume {
   background-image:url("images/resknd/default/16x16/PhysicalSANAdapter_NFSVolume.png") !important;
}

.resknd_default_vcenteroperationsadapter_vc-ops-remote-collector {
   background-image:url("images/resknd/default/16x16/vCenter Operations Adapter_vC-Ops-Remote-Collector.png") !important;
}

.resknd_default_nsxtadapter_logicalroutergroup {
   background-image:url("images/resknd/default/16x16/NSXTAdapter_LogicalRouterGroup.png") !important;
}

.resknd_default_vmware_datastorefolder {
   background-image:url("images/resknd/default/16x16/VMWARE_DatastoreFolder.png") !important;
}

.resknd_default_nsxtadapter_nsxtadapterinstance {
   background-image:url("images/resknd/default/16x16/NSXTAdapter_NSXTAdapterInstance.png") !important;
}

.resknd_custom_apposucp_ceph {
   background-image:url("images/resknd/custom/16x16/APPOSUCP_ceph.png") !important;
}

.resknd_custom_apposucp_redis {
   background-image:url("images/resknd/custom/16x16/APPOSUCP_redis.png") !important;
}

.resknd_custom_apposucp_twemproxy {
   background-image:url("images/resknd/custom/16x16/APPOSUCP_twemproxy.png") !important;
}

.resknd_custom_container_function {
   background-image:url("images/resknd/custom/16x16/Container_Function.png") !important;
}

.resknd_default_nsxtadapter_logicalswitchgroup {
   background-image:url("images/resknd/default/16x16/NSXTAdapter_LogicalSwitchGroup.png") !important;
}

.resknd_default_vcenteroperationsadapter_vc-ops-product-ui {
   background-image:url("images/resknd/default/16x16/vCenter Operations Adapter_vC-Ops-Product-UI.png") !important;
}

.resknd_custom_apposucp_jenkins {
   background-image:url("images/resknd/custom/16x16/APPOSUCP_jenkins.png") !important;
}

.resknd_custom_apposucp_sharepoint_web_server {
   background-image:url("images/resknd/custom/16x16/APPOSUCP_sharepoint_web_server.png") !important;
}

.resknd_default_nsxtadapter_loadbalancervirtualservergroup {
   background-image:url("images/resknd/default/16x16/NSXTAdapter_LoadBalancerVirtualServerGroup.png") !important;
}

.resknd_custom_apposucp_activedirectory_security {
   background-image:url("images/resknd/custom/16x16/APPOSUCP_activedirectory_security.png") !important;
}

.resknd_custom_apposucp_consul {
   background-image:url("images/resknd/custom/16x16/APPOSUCP_consul.png") !important;
}

.resknd_custom_apposucp_netresponse_tcp {
   background-image:url("images/resknd/custom/16x16/APPOSUCP_netresponse_tcp.png") !important;
}

.resknd_default_fabricserver_activezoneset {
   background-image:url("images/resknd/default/16x16/FabricServer_ActiveZoneSet.png") !important;
}

.resknd_default_vmware_hostsystem {
   background-image:url("images/resknd/default/16x16/VMWARE_HostSystem.png") !important;
}

.resknd_default_vmware_virtualmachine_power_unknown {
   background-image:url("images/resknd/default/16x16/VMWARE_VirtualMachine_power_unknown.png") !important;
}

.resknd_default_vmware_clustercomputeresource {
   background-image:url("images/resknd/default/16x16/VMWARE_ClusterComputeResource.png") !important;
}

.trvspec_default_edgeservices {
   background-image:url("images/traversalspec/16x16/EdgeServices.png") !important;
}

.resknd_default_fabricserver_physicalsanfabricinstance {
   background-image:url("images/resknd/default/16x16/FabricServer_Physical SAN Fabric Instance.png") !important;
}

.trvspec_default_fabricview {
   background-image:url("images/traversalspec/16x16/FabricView.png") !important;
}

.resknd_default_vmware_vsphereworld {
   background-image:url("images/resknd/default/16x16/VMWARE_vSphere World.png") !important;
}

.trvspec_default_vcactenantview-vcacadapter-tenant {
   background-image:url("images/traversalspec/16x16/vCAC Tenant View-VCACAdapter-TENANT.png") !important;
}

.resknd_default_nsxtadapter_tier1logicalroutergroup {
   background-image:url("images/resknd/default/16x16/NSXTAdapter_Tier1LogicalRouterGroup.png") !important;
}

.resknd_default_nsxtadapter_logicalrouter {
   background-image:url("images/resknd/default/16x16/NSXTAdapter_LogicalRouter.png") !important;
}

.resknd_default_vmware_datastore_power_off {
   background-image:url("images/resknd/default/16x16/VMWARE_Datastore_power_off.png") !important;
}

.resknd_custom_apposucp_marathon {
   background-image:url("images/resknd/custom/16x16/APPOSUCP_marathon.png") !important;
}

.resknd_custom_apposucp_weblogic_jms_runtime {
   background-image:url("images/resknd/custom/16x16/APPOSUCP_weblogic_jms_runtime.png") !important;
}

.resknd_default_vcacadapter_reservation {
   background-image:url("images/resknd/default/16x16/VCACAdapter_RESERVATION.png") !important;
}

.adpknd_custom_voaadapter {
   background-image:url("images/adpknd/custom/16x16/VOAAdapter.png") !important;
}

.resknd_default_vcacadapter_storagereservationpolicy {
   background-image:url("images/resknd/default/16x16/VCACAdapter_STORAGERESERVATIONPOLICY.png") !important;
}

.resknd_custom_apposucp_activedirectory_dns {
   background-image:url("images/resknd/custom/16x16/APPOSUCP_activedirectory_dns.png") !important;
}

.resknd_default_epopsadapter_linux_networkserverinterface {
   background-image:url("images/resknd/default/16x16/EP Ops Adapter_Linux_NetworkServer Interface.png") !important;
}

.resknd_custom_apposucp_chef {
   background-image:url("images/resknd/custom/16x16/APPOSUCP_chef.png") !important;
}

.resknd_default_physicalsanadapter_hostadapter {
   background-image:url("images/resknd/default/16x16/PhysicalSANAdapter_HostAdapter.png") !important;
}

.adpknd_custom_httppost {
   background-image:url("images/adpknd/custom/16x16/Http Post.png") !important;
}

.resknd_custom_apposucp_activemq_os {
   background-image:url("images/resknd/custom/16x16/APPOSUCP_activemq_os.png") !important;
}

.resknd_default_apposucp_apache {
   background-image:url("images/resknd/default/16x16/APPOSUCP_apache.png") !important;
}

.resknd_default_epopsadapter_windows_fileserverdirectorytree {
   background-image:url("images/resknd/default/16x16/EP Ops Adapter_Windows_FileServer Directory Tree.png") !important;
}

.resknd_custom_apposucp_hadoop-yarn {
   background-image:url("images/resknd/custom/16x16/APPOSUCP_hadoop-yarn.png") !important;
}

.resknd_custom_container_universe {
   background-image:url("images/resknd/custom/16x16/Container_Universe.png") !important;
}

.resknd_default_apposucp_nginx {
   background-image:url("images/resknd/default/16x16/APPOSUCP_nginx.png") !important;
}

.resknd_default_physicalsanadapter_physicalsanadapterinstance {
   background-image:url("images/resknd/default/16x16/PhysicalSANAdapter_PhysicalSANAdapter Instance.png") !important;
}

.resknd_custom_apposucp_msexchange_domain_controller {
   background-image:url("images/resknd/custom/16x16/APPOSUCP_msexchange_domain_controller.png") !important;
}

.adpknd_custom_epopsadapter {
   background-image:url("images/adpknd/custom/16x16/EP Ops Adapter.png") !important;
}

.adpknd_custom_openapi {
   background-image:url("images/adpknd/custom/16x16/OPENAPI.png") !important;
}

.resknd_default_apposucp_activedirectory {
   background-image:url("images/resknd/default/16x16/APPOSUCP_activedirectory.png") !important;
}

.resknd_default_vmware_virtualmachine {
   background-image:url("images/resknd/default/16x16/VMWARE_VirtualMachine.png") !important;
}

.resknd_default_nsxtadapter_firewallsection {
   background-image:url("images/resknd/default/16x16/NSXTAdapter_FirewallSection.png") !important;
}

.resknd_custom_openapi_openapiadapterinstance {
   background-image:url("images/resknd/custom/16x16/OPENAPI_OPENAPI Adapter Instance.png") !important;
}

.resknd_default_epopsadapter_linux_fileserverlogicaldisk {
   background-image:url("images/resknd/default/16x16/EP Ops Adapter_Linux_FileServer Logical Disk.png") !important;
}

.resknd_custom_apposucp_elasticsearch {
   background-image:url("images/resknd/custom/16x16/APPOSUCP_elasticsearch.png") !important;
}

.resknd_custom_apposucp_fluentd {
   background-image:url("images/resknd/custom/16x16/APPOSUCP_fluentd.png") !important;
}

.resknd_custom_container_containeradapterinstance {
   background-image:url("images/resknd/custom/16x16/Container_ContainerAdapterInstance.png") !important;
}

.resknd_default_epopsadapter_solaris_cpu {
   background-image:url("images/resknd/default/16x16/EP Ops Adapter_Solaris_CPU.png") !important;
}

.resknd_custom_apposucp_hadoop-mapreduce {
   background-image:url("images/resknd/custom/16x16/APPOSUCP_hadoop-mapreduce.png") !important;
}

.resknd_custom_apposucp_ucpserver {
   background-image:url("images/resknd/custom/16x16/APPOSUCP_UCPSERVER.png") !important;
}

.resknd_custom_nsxtadapter_managementservicegroup {
   background-image:url("images/resknd/custom/16x16/NSXTAdapter_ManagementServiceGroup.png") !important;
}

.trvspec_default_vcactenant-deployment-vmview-vcacadapter-tenant {
   background-image:url("images/traversalspec/16x16/vCAC Tenant-Deployment-VM View-VCACAdapter-TENANT.png") !important;
}

.resknd_default_apposucp_msiis {
   background-image:url("images/resknd/default/16x16/APPOSUCP_msiis.png") !important;
}

.resknd_custom_apposucp_rabbitmq_exchange {
   background-image:url("images/resknd/custom/16x16/APPOSUCP_rabbitmq_exchange.png") !important;
}

.resknd_custom_apposucp_rabbitmq_virtual_host {
   background-image:url("images/resknd/custom/16x16/APPOSUCP_rabbitmq_virtual_host.png") !important;
}

.resknd_custom_apposucp_activedirectory_database {
   background-image:url("images/resknd/custom/16x16/APPOSUCP_activedirectory_database.png") !important;
}

.resknd_default_epopsadapter_solaris_fileserverdirectorytree {
   background-image:url("images/resknd/default/16x16/EP Ops Adapter_Solaris_FileServer Directory Tree.png") !important;
}

.resknd_default_epopsadapter_aix_fileserverlogicaldisk {
   background-image:url("images/resknd/default/16x16/EP Ops Adapter_AIX_FileServer Logical Disk.png") !important;
}

.resknd_default_nsxtadapter_logicalswitch {
   background-image:url("images/resknd/default/16x16/NSXTAdapter_LogicalSwitch.png") !important;
}

.resknd_default_epopsadapter_solaris_fileserverblockdevice {
   background-image:url("images/resknd/default/16x16/EP Ops Adapter_Solaris_FileServer Block Device.png") !important;
}

.resknd_default_epopsadapter_operatingsystemsworld {
   background-image:url("images/resknd/default/16x16/EP Ops Adapter_Operating Systems World.png") !important;
}

.adpknd_custom_container {
   background-image:url("images/adpknd/custom/16x16/Container.png") !important;
}

.resknd_default_nsxtadapter_managementcluster {
   background-image:url("images/resknd/default/16x16/NSXTAdapter_ManagementCluster.png") !important;
}

.resknd_custom_apposucp_ping {
   background-image:url("images/resknd/custom/16x16/APPOSUCP_ping.png") !important;
}

.resknd_default_vmware_vmwareadapterinstance {
   background-image:url("images/resknd/default/16x16/VMWARE_VMwareAdapter Instance.png") !important;
}

.trvspec_default_nsx-tcontrolplane-nsxtadapter-nsxtadapterinstance {
   background-image:url("images/traversalspec/16x16/NSX-T Control Plane-NSXTAdapter-NSXTAdapterInstance.png") !important;
}

.resknd_custom_ucsmadapter_ucsmadapterinstance {
   background-image:url("images/resknd/custom/16x16/UCSMAdapter_UCSMAdapter Instance.png") !important;
}

.resknd_custom_loginsight_loginsightauth {
   background-image:url("images/resknd/custom/16x16/LogInsight_LogInsightAuth.png") !important;
}

.resknd_custom_apposucp_weblogic_jvm_memory {
   background-image:url("images/resknd/custom/16x16/APPOSUCP_weblogic_jvm_memory.png") !important;
}

.resknd_default_apposucp_riak {
   background-image:url("images/resknd/default/16x16/APPOSUCP_riak.png") !important;
}

.resknd_default_vmware_datastore_power_unknown {
   background-image:url("images/resknd/default/16x16/VMWARE_Datastore_power_unknown.png") !important;
}

.resknd_custom_apposucp_msexchange_win_service {
   background-image:url("images/resknd/custom/16x16/APPOSUCP_msexchange_win_service.png") !important;
}

.trvspec_default_vspherenetworking-vmware-vsphereworld {
   background-image:url("images/traversalspec/16x16/vSphere Networking-VMWARE-vSphere World.png") !important;
}

.resknd_default_apposucp_tomcat {
   background-image:url("images/resknd/default/16x16/APPOSUCP_tomcat.png") !important;
}

.resknd_default_vmware_hostsystem_power_off {
   background-image:url("images/resknd/default/16x16/VMWARE_HostSystem_power_off.png") !important;
}

.adpknd_custom_vrealizeopsmgrapi {
   background-image:url("images/adpknd/custom/16x16/vRealizeOpsMgrAPI.png") !important;
}

.trvspec_default_nsx-tlogicalrouters-nsxtadapter-nsxtadapterinstance {
   background-image:url("images/traversalspec/16x16/NSX-T Logical Routers-NSXTAdapter-NSXTAdapterInstance.png") !important;
}

.resknd_default_pythonremediationvcenteradapter_pythonremediationvcenteradapterinstance {
   background-image:url("images/resknd/default/16x16/PythonRemediationVcenterAdapter_PythonRemediationVcenterAdapter Instance.png") !important;
}

.trvspec_default_vcactenant-blueprintview-vcacadapter-tenant {
   background-image:url("images/traversalspec/16x16/vCAC Tenant-Blueprint View-VCACAdapter-TENANT.png") !important;
}

.resknd_default_epopsadapter_epopsagent {
   background-image:url("images/resknd/default/16x16/EP Ops Adapter_EP Ops Agent.png") !important;
}

.resknd_default_vmware_hostsystem_power_standby {
   background-image:url("images/resknd/default/16x16/VMWARE_HostSystem_power_standby.png") !important;
}

.resknd_custom_apposucp_etcd {
   background-image:url("images/resknd/custom/16x16/APPOSUCP_etcd.png") !important;
}

.adpknd_default_vcacadapter {
   background-image:url("images/adpknd/default/16x16/VCACAdapter.png") !important;
}

.resknd_default_apposucp_mongodb {
   background-image:url("images/resknd/default/16x16/APPOSUCP_mongodb.png") !important;
}

.resknd_default_epopsadapter_windows {
   background-image:url("images/resknd/default/16x16/EP Ops Adapter_Windows.png") !important;
}

.adpknd_default_vcenteroperationsadapter {
   background-image:url("images/adpknd/default/16x16/vCenter Operations Adapter.png") !important;
}

.resknd_default_vmware_hostfolder {
   background-image:url("images/resknd/default/16x16/VMWARE_HostFolder.png") !important;
}

.resknd_default_epopsadapter_aix_fileserverdirectorytree {
   background-image:url("images/resknd/default/16x16/EP Ops Adapter_AIX_FileServer Directory Tree.png") !important;
}

.resknd_default_vmware_storagepod {
   background-image:url("images/resknd/default/16x16/VMWARE_StoragePod.png") !important;
}

.resknd_custom_epopsadapter_hpux {
   background-image:url("images/resknd/custom/16x16/EP Ops Adapter_HPUX.png") !important;
}

.resknd_default_epopsadapter_windows_fileserverdirectory {
   background-image:url("images/resknd/default/16x16/EP Ops Adapter_Windows_FileServer Directory.png") !important;
}

.resknd_custom_apposucp_pivotalserver_threadpool {
   background-image:url("images/resknd/custom/16x16/APPOSUCP_pivotalserver_threadpool.png") !important;
}

.resknd_default_fabricserver_logicalswitch {
   background-image:url("images/resknd/default/16x16/FabricServer_LogicalSwitch.png") !important;
}

.resknd_default_epopsadapter_windows_fileserverblockdevice {
   background-image:url("images/resknd/default/16x16/EP Ops Adapter_Windows_FileServer Block Device.png") !important;
}

.resknd_custom_apposucp_apachemesos {
   background-image:url("images/resknd/custom/16x16/APPOSUCP_apachemesos.png") !important;
}

.resknd_default_vmware_virtualmachine_power_on {
   background-image:url("images/resknd/default/16x16/VMWARE_VirtualMachine_power_on.png") !important;
}

.resknd_default_epopsadapter_aix_cpu {
   background-image:url("images/resknd/default/16x16/EP Ops Adapter_AIX_CPU.png") !important;
}

.adpknd_default_loginsightadapter {
   background-image:url("images/adpknd/default/16x16/LogInsightAdapter.png") !important;
}

.resknd_default_vcenteroperationsadapter_vc-ops-watchdog {
   background-image:url("images/resknd/default/16x16/vCenter Operations Adapter_vC-Ops-Watchdog.png") !important;
}

.resknd_custom_apposucp_haproxy {
   background-image:url("images/resknd/custom/16x16/APPOSUCP_haproxy.png") !important;
}

.resknd_custom_apposucp_phpfpm {
   background-image:url("images/resknd/custom/16x16/APPOSUCP_phpfpm.png") !important;
}

.resknd_custom_apposucp_weblogic_jta_runtime {
   background-image:url("images/resknd/custom/16x16/APPOSUCP_weblogic_jta_runtime.png") !important;
}

.trvspec_default_vcopsclusters-vcenteroperationsadapter-vc-ops-cluster {
   background-image:url("images/traversalspec/16x16/vC Ops Clusters-vCenter Operations Adapter-vC-Ops-Cluster.png") !important;
}

.resknd_custom_container_environment {
   background-image:url("images/resknd/custom/16x16/Container_Environment.png") !important;
}

.resknd_custom_container_windows {
   background-image:url("images/resknd/custom/16x16/Container_Windows.png") !important;
}

.resknd_custom_apposucp_msexchange_web_server {
   background-image:url("images/resknd/custom/16x16/APPOSUCP_msexchange_web_server.png") !important;
}

.resknd_default_vcenteroperationsadapter_vc-ops-casa {
   background-image:url("images/resknd/default/16x16/vCenter Operations Adapter_vC-Ops-CaSA.png") !important;
}

.resknd_default_epopsadapter_solaris_fileserverdirectory {
   background-image:url("images/resknd/default/16x16/EP Ops Adapter_Solaris_FileServer Directory.png") !important;
}

.resknd_custom_container_aimplugin {
   background-image:url("images/resknd/custom/16x16/Container_AIM Plugin.png") !important;
}

.resknd_default_vmware_customdatacenter {
   background-image:url("images/resknd/default/16x16/VMWARE_CustomDatacenter.png") !important;
}

.trvspec_default_customdatacenters-vmware-customdatacenter {
   background-image:url("images/traversalspec/16x16/Custom Datacenters-VMWARE-CustomDatacenter.png") !important;
}

.adpknd_default_vmware {
   background-image:url("images/adpknd/default/16x16/VMWARE.png") !important;
}

.resknd_default_epopsadapter_windows_cpu {
   background-image:url("images/resknd/default/16x16/EP Ops Adapter_Windows_CPU.png") !important;
}

.resknd_default_epopsadapter_windows_fileserverfile {
   background-image:url("images/resknd/default/16x16/EP Ops Adapter_Windows_FileServer File.png") !important;
}

.resknd_custom_vcacadapter_user {
   background-image:url("images/resknd/custom/16x16/VCACAdapter_USER.png") !important;
}

.resknd_custom_apposucp_ms_iis_http_queues {
   background-image:url("images/resknd/custom/16x16/APPOSUCP_ms_iis_http_queues.png") !important;
}

.resknd_custom_vcacadapter_vraworld {
   background-image:url("images/resknd/custom/16x16/VCACAdapter_vRA World.png") !important;
}

.resknd_default_vmware_hostsystem_power_on {
   background-image:url("images/resknd/default/16x16/VMWARE_HostSystem_power_on.png") !important;
}

.resknd_custom_apposucp_activemq_topic {
   background-image:url("images/resknd/custom/16x16/APPOSUCP_activemq_topic.png") !important;
}

.resknd_default_nsxtadapter_transportnode {
   background-image:url("images/resknd/default/16x16/NSXTAdapter_TransportNode.png") !important;
}

.resknd_custom_apposucp_ms_iis_win_proc {
   background-image:url("images/resknd/custom/16x16/APPOSUCP_ms_iis_win_proc.png") !important;
}

.resknd_custom_apposucp_activedirectory_services {
   background-image:url("images/resknd/custom/16x16/APPOSUCP_activedirectory_services.png") !important;
}

.resknd_custom_apposucp_msexchange_database {
   background-image:url("images/resknd/custom/16x16/APPOSUCP_msexchange_database.png") !important;
}

.resknd_default_vcenteroperationsadapter_vc-ops-admin-ui {
   background-image:url("images/resknd/default/16x16/vCenter Operations Adapter_vC-Ops-Admin-UI.png") !important;
}

.resknd_default_vcacadapter_tenant {
   background-image:url("images/resknd/default/16x16/VCACAdapter_TENANT.png") !important;
}

.resknd_custom_apposucp_bitbucket {
   background-image:url("images/resknd/custom/16x16/APPOSUCP_bitbucket.png") !important;
}

.resknd_custom_nsxtadapter_nsservice {
   background-image:url("images/resknd/custom/16x16/NSXTAdapter_NSService.png") !important;
}

.resknd_custom_epopsadapter_remotechecksworld {
   background-image:url("images/resknd/custom/16x16/EP Ops Adapter_Remote Checks World.png") !important;
}

.resknd_custom_apposucp_websphere {
   background-image:url("images/resknd/custom/16x16/APPOSUCP_websphere.png") !important;
}

.resknd_custom_container_vmvra {
   background-image:url("images/resknd/custom/16x16/Container_VM vRA.png") !important;
}

.resknd_custom_apposucp_jboss_jvm_memory {
   background-image:url("images/resknd/custom/16x16/APPOSUCP_jboss_jvm_memory.png") !important;
}

.resknd_custom_loginsight_loginsightlogserverhost {
   background-image:url("images/resknd/custom/16x16/LogInsight_LogInsightLogServerHost.png") !important;
}

.resknd_default_epopsadapter_linux_fileserverfile {
   background-image:url("images/resknd/default/16x16/EP Ops Adapter_Linux_FileServer File.png") !important;
}

.trvspec_default_physicalsan-physicalsanadapter-physicalsanadapterinstance {
   background-image:url("images/traversalspec/16x16/Physical SAN-PhysicalSANAdapter-PhysicalSANAdapter Instance.png") !important;
}

.resknd_custom_apposucp_msexchange_database_instance {
   background-image:url("images/resknd/custom/16x16/APPOSUCP_msexchange_database_instance.png") !important;
}

.resknd_default_epopsadapter_aix_fileserverfile {
   background-image:url("images/resknd/default/16x16/EP Ops Adapter_AIX_FileServer File.png") !important;
}

.resknd_default_vmware_datacenter {
   background-image:url("images/resknd/default/16x16/VMWARE_Datacenter.png") !important;
}

.resknd_default_epopsadapter_tcpcheck {
   background-image:url("images/resknd/default/16x16/EP Ops Adapter_TCP Check.png") !important;
}

.resknd_custom_apposucp_zookeeper {
   background-image:url("images/resknd/custom/16x16/APPOSUCP_zookeeper.png") !important;
}

.resknd_default_epopsadapter_linux_fileserverblockdevice {
   background-image:url("images/resknd/default/16x16/EP Ops Adapter_Linux_FileServer Block Device.png") !important;
}

.resknd_custom_apposucp_activedirectory_dfsn {
   background-image:url("images/resknd/custom/16x16/APPOSUCP_activedirectory_dfsn.png") !important;
}

.resknd_custom_apposucp_postgresql_database {
   background-image:url("images/resknd/custom/16x16/APPOSUCP_postgresql_database.png") !important;
}

.resknd_custom_apposucp_mongodb_databases {
   background-image:url("images/resknd/custom/16x16/APPOSUCP_mongodb_databases.png") !important;
}

.resknd_custom_container_location {
   background-image:url("images/resknd/custom/16x16/Container_Location.png") !important;
}

.resknd_default_apposucp_mssql {
   background-image:url("images/resknd/default/16x16/APPOSUCP_mssql.png") !important;
}

.resknd_custom_epopsadapter_epopsadapterinstance {
   background-image:url("images/resknd/custom/16x16/EP Ops Adapter_EP Ops Adapter Instance.png") !important;
}

.resknd_default_vcacadapter_fabricgroup {
   background-image:url("images/resknd/default/16x16/VCACAdapter_FABRICGROUP.png") !important;
}

.resknd_default_fabricserver_san {
   background-image:url("images/resknd/default/16x16/FabricServer_San.png") !important;
}

.resknd_default_epopsadapter_script {
   background-image:url("images/resknd/default/16x16/EP Ops Adapter_Script.png") !important;
}

.resknd_default_vcenteroperationsadapter_vc-ops-collector {
   background-image:url("images/resknd/default/16x16/vCenter Operations Adapter_vC-Ops-Collector.png") !important;
}

.resknd_default_vmware_datastore_power_standby {
   background-image:url("images/resknd/default/16x16/VMWARE_Datastore_power_standby.png") !important;
}

.adpknd_default_fabricserver {
   background-image:url("images/adpknd/default/16x16/FabricServer.png") !important;
}

.resknd_custom_apposucp_weblogic_garbage_collector {
   background-image:url("images/resknd/custom/16x16/APPOSUCP_weblogic_garbage_collector.png") !important;
}

.trvspec_default_vcaccdcview-vmware-customdatacenter {
   background-image:url("images/traversalspec/16x16/vCAC CDC View-VMWARE-CustomDatacenter.png") !important;
}

.resknd_custom_vcenteroperationsadapter_vc-ops-managementpack {
   background-image:url("images/resknd/custom/16x16/vCenter Operations Adapter_vC-Ops-ManagementPack.png") !important;
}

.trvspec_default_edgenodes {
   background-image:url("images/traversalspec/16x16/EdgeNodes.png") !important;
}

.adpknd_default_nsxtadapter {
   background-image:url("images/adpknd/default/16x16/NSXTAdapter.png") !important;
}

.resknd_default_vcenteroperationsadapter_vc-ops-managementpackgroup {
   background-image:url("images/resknd/default/16x16/vCenter Operations Adapter_vC-Ops-ManagementPackGroup.png") !important;
}

.resknd_default_nsxtadapter_firewallsectiongroup {
   background-image:url("images/resknd/default/16x16/NSXTAdapter_FirewallSectionGroup.png") !important;
}

.resknd_custom_apposucp_hyperv {
   background-image:url("images/resknd/custom/16x16/APPOSUCP_hyperv.png") !important;
}

.resknd_custom_apposucp_cassandra {
   background-image:url("images/resknd/custom/16x16/APPOSUCP_cassandra.png") !important;
}

.resknd_custom_apposucp_memcached {
   background-image:url("images/resknd/custom/16x16/APPOSUCP_memcached.png") !important;
}

.resknd_default_vcenteroperationsadapter_vc-ops-cluster {
   background-image:url("images/resknd/default/16x16/vCenter Operations Adapter_vC-Ops-Cluster.png") !important;
}

.resknd_default_apposucp_activemq {
   background-image:url("images/resknd/default/16x16/APPOSUCP_activemq.png") !important;
}

.resknd_default_apposucp_pivotalserver {
   background-image:url("images/resknd/default/16x16/APPOSUCP_pivotalserver.png") !important;
}

.resknd_custom_apposucp_jboss_datasource_pool {
   background-image:url("images/resknd/custom/16x16/APPOSUCP_jboss_datasource_pool.png") !important;
}

.resknd_default_apposucp_apposucpadapterinstance {
   background-image:url("images/resknd/default/16x16/APPOSUCP_APPOSUCPAdapterInstance.png") !important;
}

.resknd_custom_apposucp_os {
   background-image:url("images/resknd/custom/16x16/APPOSUCP_OS.png") !important;
}

.resknd_custom_apposucp_wildfly {
   background-image:url("images/resknd/custom/16x16/APPOSUCP_wildfly.png") !important;
}

.resknd_default_epopsadapter_solaris_fileservermount {
   background-image:url("images/resknd/default/16x16/EP Ops Adapter_Solaris_FileServer Mount.png") !important;
}

.resknd_default_nsxtadapter_transportzone {
   background-image:url("images/resknd/default/16x16/NSXTAdapter_TransportZone.png") !important;
}

.resknd_default_vcacadapter_entitystatus {
   background-image:url("images/resknd/default/16x16/VCACAdapter_ENTITYSTATUS.png") !important;
}

.adpknd_default_apposucp {
   background-image:url("images/adpknd/default/16x16/APPOSUCP.png") !important;
}

.trvspec_default_operatingsystemsts-epopsadapter-operatingsystemsworld {
   background-image:url("images/traversalspec/16x16/Operating Systems TS-EP Ops Adapter-Operating Systems World.png") !important;
}

.resknd_custom_apposucp_tomcat_server_web_module {
   background-image:url("images/resknd/custom/16x16/APPOSUCP_tomcat_server_web_module.png") !important;
}

.resknd_default_epopsadapter_linux_fileserverphysicaldisk {
   background-image:url("images/resknd/default/16x16/EP Ops Adapter_Linux_FileServer Physical Disk.png") !important;
}

.resknd_custom_nsxtadapter_edgenodegroup {
   background-image:url("images/resknd/custom/16x16/NSXTAdapter_EdgeNodeGroup.png") !important;
}

.resknd_default_vmware_vmfolder {
   background-image:url("images/resknd/default/16x16/VMWARE_VMFolder.png") !important;
}

.resknd_default_fabricserver_switch {
   background-image:url("images/resknd/default/16x16/FabricServer_Switch.png") !important;
}

.resknd_default_apposucp_rabbitmq {
   background-image:url("images/resknd/default/16x16/APPOSUCP_rabbitmq.png") !important;
}

.resknd_default_vcenteroperationsadapter_vc-ops-analytics {
   background-image:url("images/resknd/default/16x16/vCenter Operations Adapter_vC-Ops-Analytics.png") !important;
}

.resknd_custom_apposucp_mssql_database {
   background-image:url("images/resknd/custom/16x16/APPOSUCP_mssql_database.png") !important;
}

.resknd_custom_apposucp_sharepoint_win_service {
   background-image:url("images/resknd/custom/16x16/APPOSUCP_sharepoint_win_service.png") !important;
}

.resknd_default_physicalsanadapter_storagelun {
   background-image:url("images/resknd/default/16x16/PhysicalSANAdapter_StorageLun.png") !important;
}

.resknd_custom_apposucp_mysql_database {
   background-image:url("images/resknd/custom/16x16/APPOSUCP_mysql_database.png") !important;
}

.resknd_custom_apposucp_tomcat_server_threadpool {
   background-image:url("images/resknd/custom/16x16/APPOSUCP_tomcat_server_threadpool.png") !important;
}

.resknd_default_epopsadapter_linux {
   background-image:url("images/resknd/default/16x16/EP Ops Adapter_Linux.png") !important;
}

.resknd_custom_container_enterprise {
   background-image:url("images/resknd/custom/16x16/Container_Enterprise.png") !important;
}

.resknd_custom_apposucp_netresponse_udp {
   background-image:url("images/resknd/custom/16x16/APPOSUCP_netresponse_udp.png") !important;
}

.resknd_default_epopsadapter_linux_fileserverdirectorytree {
   background-image:url("images/resknd/default/16x16/EP Ops Adapter_Linux_FileServer Directory Tree.png") !important;
}

.resknd_custom_apposucp_weblogic_jvm_memory_pool {
   background-image:url("images/resknd/custom/16x16/APPOSUCP_weblogic_jvm_memory_pool.png") !important;
}

.resknd_default_vcacadapter_vcacadapterinstance {
   background-image:url("images/resknd/default/16x16/VCACAdapter_VCACAdapter Instance.png") !important;
}

.resknd_default_fabricserver_fabric {
   background-image:url("images/resknd/default/16x16/FabricServer_Fabric.png") !important;
}

.trvspec_default_infrastructureview {
   background-image:url("images/traversalspec/16x16/InfrastructureView.png") !important;
}

.resknd_custom_vmware_computeresource {
   background-image:url("images/resknd/custom/16x16/VMWARE_ComputeResource.png") !important;
}

.resknd_custom_apposucp_activedirectory_dfs_replication {
   background-image:url("images/resknd/custom/16x16/APPOSUCP_activedirectory_dfs_replication.png") !important;
}

.resknd_custom_apposucp_weblogic_jvm_runtime {
   background-image:url("images/resknd/custom/16x16/APPOSUCP_weblogic_jvm_runtime.png") !important;
}

.resknd_default_vcenteroperationsadapter_vcenteroperationsadapterinstance {
   background-image:url("images/resknd/default/16x16/vCenter Operations Adapter_vCenter Operations Adapter Instance.png") !important;
}

.resknd_custom_container_servicelevelobjective {
   background-image:url("images/resknd/custom/16x16/Container_Service Level Objective.png") !important;
}

.resknd_default_nsxtadapter_controllercluster {
   background-image:url("images/resknd/default/16x16/NSXTAdapter_ControllerCluster.png") !important;
}

.resknd_default_vmware_folder {
   background-image:url("images/resknd/default/16x16/VMWARE_Folder.png") !important;
}

.trvspec_default_1 {
   background-image:url("images/traversalspec/16x16/1.png") !important;
}

.resknd_custom_apposucp_jboss_jvm_memory_pool {
   background-image:url("images/resknd/custom/16x16/APPOSUCP_jboss_jvm_memory_pool.png") !important;
}

.resknd_default_physicalsanadapter_storagearray {
   background-image:url("images/resknd/default/16x16/PhysicalSANAdapter_StorageArray.png") !important;
}

.resknd_default_nsxtadapter_edgecluster {
   background-image:url("images/resknd/default/16x16/NSXTAdapter_EdgeCluster.png") !important;
}

.resknd_custom_container_vravms {
   background-image:url("images/resknd/custom/16x16/Container_vRA VMs.png") !important;
}

.resknd_default_apposucp_msexchange {
   background-image:url("images/resknd/default/16x16/APPOSUCP_msexchange.png") !important;
}

.resknd_default_apposucp_mysql {
   background-image:url("images/resknd/default/16x16/APPOSUCP_mysql.png") !important;
}

.resknd_custom_apposucp_httpresponse {
   background-image:url("images/resknd/custom/16x16/APPOSUCP_httpresponse.png") !important;
}

.resknd_default_nsxtadapter_managementappliances {
   background-image:url("images/resknd/default/16x16/NSXTAdapter_ManagementAppliances.png") !important;
}

.resknd_default_epopsadapter_solaris {
   background-image:url("images/resknd/default/16x16/EP Ops Adapter_Solaris.png") !important;
}

.trvspec_default_vcacreservationpolicyview-vcacadapter-reservationpolicy {
   background-image:url("images/traversalspec/16x16/vCAC Reservation policy View-VCACAdapter-RESERVATIONPOLICY.png") !important;
}

.resknd_custom_container_securityzone {
   background-image:url("images/resknd/custom/16x16/Container_Security Zone.png") !important;
}

.resknd_default_epopsadapter_httpcheck {
   background-image:url("images/resknd/default/16x16/EP Ops Adapter_HTTP Check.png") !important;
}

.resknd_default_epopsadapter_windows_networkserverinterface {
   background-image:url("images/resknd/default/16x16/EP Ops Adapter_Windows_NetworkServer Interface.png") !important;
}

.resknd_custom_loginsight_loginsightlogserver {
   background-image:url("images/resknd/custom/16x16/LogInsight_LogInsightLogServer.png") !important;
}

.resknd_custom_vrbcadapter_vrbcadapterinstance {
   background-image:url("images/resknd/custom/16x16/vRBCAdapter_vRBC Adapter Instance.png") !important;
}

.resknd_custom_nsxtadapter_nsservicegroups {
   background-image:url("images/resknd/custom/16x16/NSXTAdapter_NSServiceGroups.png") !important;
}

.resknd_default_vcacadapter_businessgroup {
   background-image:url("images/resknd/default/16x16/VCACAdapter_BUSINESSGROUP.png") !important;
}

.resknd_custom_apposucp_apachesolr {
   background-image:url("images/resknd/custom/16x16/APPOSUCP_apachesolr.png") !important;
}

.resknd_default_epopsadapter_linux_fileservermount {
   background-image:url("images/resknd/default/16x16/EP Ops Adapter_Linux_FileServer Mount.png") !important;
}

.resknd_default_epopsadapter_aix_fileserverblockdevice {
   background-image:url("images/resknd/default/16x16/EP Ops Adapter_AIX_FileServer Block Device.png") !important;
}

.trvspec_default_vspherestorage-vmware-vsphereworld {
   background-image:url("images/traversalspec/16x16/vSphere Storage-VMWARE-vSphere World.png") !important;
}

.resknd_default_epopsadapter_windows_fileserverphysicaldisk {
   background-image:url("images/resknd/default/16x16/EP Ops Adapter_Windows_FileServer Physical Disk.png") !important;
}

.resknd_custom_nsxtadapter_nsservicegroup {
   background-image:url("images/resknd/custom/16x16/NSXTAdapter_NSServiceGroup.png") !important;
}

.resknd_default_apposucp_win {
   background-image:url("images/resknd/default/16x16/APPOSUCP_win.png") !important;
}

.resknd_custom_voaadapter_voaadapterinstance {
   background-image:url("images/resknd/custom/16x16/VOAAdapter_VOAAdapterInstance.png") !important;
}

.resknd_custom_nsxtadapter_routerservice {
   background-image:url("images/resknd/custom/16x16/NSXTAdapter_RouterService.png") !important;
}

.resknd_custom_vcacadapter_deployment {
   background-image:url("images/resknd/custom/16x16/VCACAdapter_DEPLOYMENT.png") !important;
}

.resknd_default_epopsadapter_aix_networkserverinterface {
   background-image:url("images/resknd/default/16x16/EP Ops Adapter_AIX_NetworkServer Interface.png") !important;
}

.trvspec_default_servicetype-apposucp-servicetype {
   background-image:url("images/traversalspec/16x16/Service Type-APPOSUCP-ServiceType.png") !important;
}

.adpknd_default_physicalsanadapter {
   background-image:url("images/adpknd/default/16x16/PhysicalSANAdapter.png") !important;
}

.resknd_custom_vmware_vmentitystatus {
   background-image:url("images/resknd/custom/16x16/VMWARE_VM Entity Status.png") !important;
}

.resknd_default_epopsadapter_aix_fileserverdirectory {
   background-image:url("images/resknd/default/16x16/EP Ops Adapter_AIX_FileServer Directory.png") !important;
}

.resknd_custom_vrealizeopsmgrapi_vrealizeopsmgrapiadapterinstance {
   background-image:url("images/resknd/custom/16x16/vRealizeOpsMgrAPI_vRealizeOpsMgrAPI Adapter Instance.png") !important;
}

.resknd_custom_apposucp_jboss_jvm_garbage_collector {
   background-image:url("images/resknd/custom/16x16/APPOSUCP_jboss_jvm_garbage_collector.png") !important;
}

.resknd_custom_apposucp_varnish {
   background-image:url("images/resknd/custom/16x16/APPOSUCP_varnish.png") !important;
}

.resknd_custom_container_licensing {
   background-image:url("images/resknd/custom/16x16/Container_Licensing.png") !important;
}

.resknd_custom_apposucp_ms_iis_websvc {
   background-image:url("images/resknd/custom/16x16/APPOSUCP_ms_iis_websvc.png") !important;
}

.resknd_default_epopsadapter_solaris_fileserverlogicaldisk {
   background-image:url("images/resknd/default/16x16/EP Ops Adapter_Solaris_FileServer Logical Disk.png") !important;
}

.resknd_default_vmware_resourcepool {
   background-image:url("images/resknd/default/16x16/VMWARE_ResourcePool.png") !important;
}

.resknd_default_vmware_distributedvirtualportgroup {
   background-image:url("images/resknd/default/16x16/VMWARE_DistributedVirtualPortgroup.png") !important;
}

.resknd_custom_apposucp_lighttpd {
   background-image:url("images/resknd/custom/16x16/APPOSUCP_lighttpd.png") !important;
}

.resknd_custom_apposucp_nginxplus {
   background-image:url("images/resknd/custom/16x16/APPOSUCP_nginxplus.png") !important;
}

.resknd_default_nsxtadapter_tier0logicalroutergroup {
   background-image:url("images/resknd/default/16x16/NSXTAdapter_Tier0LogicalRouterGroup.png") !important;
}

.resknd_default_epopsadapter_process {
   background-image:url("images/resknd/default/16x16/EP Ops Adapter_Process.png") !important;
}

.resknd_default_nsxtadapter_controllernode {
   background-image:url("images/resknd/default/16x16/NSXTAdapter_ControllerNode.png") !important;
}

.resknd_default_nsxtadapter_managementservice {
   background-image:url("images/resknd/default/16x16/NSXTAdapter_ManagementService.png") !important;
}

.resknd_default_vmware_datastore_power_on {
   background-image:url("images/resknd/default/16x16/VMWARE_Datastore_power_on.png") !important;
}

.resknd_default_physicalsanadapter_storageprocessor {
   background-image:url("images/resknd/default/16x16/PhysicalSANAdapter_StorageProcessor.png") !important;
}

.resknd_default_apposucp_linux {
   background-image:url("images/resknd/default/16x16/APPOSUCP_linux.png") !important;
}

.resknd_default_vcacadapter_reservationpolicy {
   background-image:url("images/resknd/default/16x16/VCACAdapter_RESERVATIONPOLICY.png") !important;
}

.resknd_default_nsxtadapter_loadbalancerservice {
   background-image:url("images/resknd/default/16x16/NSXTAdapter_LoadBalancerService.png") !important;
}

.resknd_default_vmware_virtualmachine_power_off {
   background-image:url("images/resknd/default/16x16/VMWARE_VirtualMachine_power_off.png") !important;
}

.resknd_default_vmware_vmwaredistributedvirtualswitch {
   background-image:url("images/resknd/default/16x16/VMWARE_VmwareDistributedVirtualSwitch.png") !important;
}

.resknd_default_epopsadapter_windows_fileserverlogicaldisk {
   background-image:url("images/resknd/default/16x16/EP Ops Adapter_Windows_FileServer Logical Disk.png") !important;
}
